[build]
# Install build essentials and required compilers during the build phase
prebuild = "apt-get update && apt-get install -y build-essential python3 python3-pip openjdk-17-jdk gcc g++"
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm install && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10