[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[environment]
PORT = "3000"
NODE_ENV = "production"

[nixpacks]
nodejs_version = "18"